### ISSUE TITLE
Fill in the sequences in GFA from FASTA

### ISSUE THREAD

**Issue by sjackman** [ggonnella/gfapy#7] opened 2018-08-16 00:27 UTC
I have a GFA file produce by Canu that has `*` in the sequences. It also produces a corresponding FASTA file. Is it possible with `gfapy` to fill in the sequences in the GFA file with the sequences in the FASTA file?

**Comment by ggonnella** [comment] 2018-08-29 09:48
Hi Shaun @sjackman. I just read your msg (I was in holiday for a few days).
I think it can be done. The problem lies only in parsing the fasta (which is not so difficult anyway, also without external libraries) and associating sequence IDs to segment names (which depends on how Canu output it). Do you have a ready example (graph/fasta) to send me?

**Comment by ggonnella** [comment] 2018-08-29 12:56
The following script should solve the task:

https://gist.github.com/ggonnella/055862bc86cb4325b52550cab1ad6ed0

Please test it, if possible, as I did not yet time to do it thoroughly.

**Comment by sjackman** [comment] 2018-08-29 17:36
Thanks for the script! I've tested it out, and it works to fill in the sequence in the segment lines!

Something odd happens to the CIGAR strings of the link lines though. All the `I` operations are changed to `D` and all the `D` to `I`. For example…
```diff
- L	tig00000004	+	tig00000005	+	27M2I22M1I2M1I9M1D3M
+ L	tig00000004	+	tig00000005	+	27M2D22M1D2M1D9M1I3M
```

**Comment by sjackman** [comment] 2018-08-29 17:57
Would you consider adding this script to `bin/gfapy-fillseq`?

My preference is for positional parameters to be input files, and output files to be specified by `-o, --output` or written to `stdout` and redirected to a file.

**Comment by ggonnella** [comment] 2018-08-30 08:15
> Would you consider adding this script to bin/gfapy-fillseq?

Yes, I will. Good idea to use -o, I usually do this as well.

> Something odd happens to the CIGAR strings of the link lines though. All the I operations are changed to D and all the D to I. For example…

Crazy! and I can't reproduce it on my examples...

**Comment by sjackman** [comment] 2018-08-30 17:42
Oh, I know what's happening. Canu is including both the forward orientation edge and the reverse orientation edge in the GFA file. gfapy is outputting the forward orientation edge, but with the CIGAR string from the reverse orientation edge. Here's the FASTA and GFA from Canu to help you troubleshoot. (note: I've replaced all the sequence with `A`s to both redact the sequence and make it compress smaller)

[canu.unitigs.fasta.gz](https://github.com/ggonnella/gfapy/files/2337275/canu.unitigs.fasta.gz)
[canu.unitigs.gfa.gz](https://github.com/ggonnella/gfapy/files/2337276/canu.unitigs.gfa.gz)

**Comment by ggonnella** [comment] 2021-06-04 10:49
I close this issue now, and will add the script I wrote back then (with a slight modification) to the repository and some simple example data. Newer versions of Canu do not output a GFA anymore, as far as I know, so the issue is not relevant.

**Closed** 2021-06-04 10:50 UTC
